version: "3.8"
services:
  db:
    build: ./models
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    restart: always

  web:
    build: ./
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "5004:5004"
    depends_on:
      - db
    restart: on-failure